### ISSUE TITLE
fit() got an unexpected keyword argument 'eval_set'

### ISSUE THREAD

**Issue by finetrade** [ScottFreeLLC/AlphaPy#12]
When I run Kaggle example I got error message:

File "/home/******/anaconda/lib/python2.7/site-packages/alphapy/model.py", line 723, in first_fit
    early_stopping_rounds=esr)
TypeError: fit() got an unexpected keyword argument 'eval_set'

**Comment by mrconway** [comment]
The software runs only on Python 3.

**Comment by finetrade** [comment]
I started Kaggle example yesterday, and it still shows: 
[09/27/17 12:12:07] INFO	No RFE Available for XGB
[09/27/17 12:12:07] INFO	Randomized Grid Search

XGB grid search takes so long time?

**Comment by mrconway** [comment]
We need to add RFE for XGB, so we'll keep this open.

**Comment by mrconway** [comment]
You can use RFECV with XGBoost now, just make sure that *scoring* is set to **True** in the *algos.yml* file for XGB.
