### ISSUE TITLE
AI to Metatrader 4

### ISSUE THREAD

**Issue by ConsultingSecurty** [ScottFreeLLC/AlphaPy#19]
Hello,

I'm interested in your application.

I want the AI for Metatrader 4. My idea is to use Google Servers and this Technology from Google to handle a Website that clone Metatrader4 library. To clone Website you have to import this code from that is listed on this site: https://www.mql5.com/de/articles/3024?utm_source=MetaTrader+4+WebTerminal&utm_campaign=Share+WebTerminal

Other Forum about this project: https://www.mql5.com/de/forum/223405

Can you do this as Opensource?

**Comment by mrconway** [comment]
Thanks for your message. This is outside the scope of our framework.

**Comment by ConsultingSecurty** [comment]
AlphaPy has been developed primarily for supervised learning tasks. You can generate models for any classification or regression problem.

I have from mql5 the terminal of MT4 / 5 on my domain as WordPress page inframed. Customers can connect their accounts there and follow the chart. I do not store any customer data.
I want to install AlphaPy there and give the chart images AlphaPy as Input. I want to involve hardware of the clientele. Even I do not want to involve hardware or store data. But I'm not a programmer and need help with the implementation.
