### ISSUE TITLE
Data is not pulling from internet

### ISSUE THREAD

**Issue by ActIII** [ScottFreeLLC/AlphaPy#7]
<img width="422" alt="screen shot 2017-06-24 at 11 38 21 am" src="https://user-images.githubusercontent.com/17787783/27509750-bd544888-58d1-11e7-977b-cdfb23839f7f.png">

When I run mflow on the tutorial "trading model" for some reason this code that is trying to receive the data just goes to the else. Is there something im doing wrong? Thanks in advance for the help!

**Comment by mrconway** [comment]
Make sure you have the latest release 2.0.1, and your market.yml has the schema **google**.

market:
    data_history    : 500
    forecast_period : 1
    fractal         : 1d
    leaders         : []
    predict_history : 100
    schema          : google
    target_group    : tech

Let me know what happens.

**Comment by ActIII** [comment]
Sweet thanks! The issue was the schema. For some reason it was set to "prices". Thanks for the quick reply

**Comment by mrconway** [comment]
You're welcome. We're still looking for a consistent, end-of-day provider after the Yahoo Finance service was discontinued. There's no telling how long Google will continue to provide these data, so any good alternatives are welcome.
